[book]
authors = ["ZoomQuiet"]
language = "en"
multilingual = false
src = "src"
title = "Weekly for China Rustaceans"
base_url = "weekly.rs.101.so"

# Enables the `mdbook-template` preprocessor
#[preprocessor.template]

[build]
build-dir = "docs"
